feat: added directory and files for rostest
AutoModality/am_super pull request #38
Opened 2020-07-18 05:46 UTC by dillonroller

2020-07-19 22:38 UTC, aroller commented on .vscode/c_cpp_properties.json
> +{
delete this file and add .vscode to your ~/.gitignore_global

2020-07-19 22:39 UTC, aroller commented on rostest/super_node_status.cpp
> +int ARMED_count = 3;
following the ROS style Guide for naming.  Mixed caps and lower is not a thing. http://wiki.ros.org/CppStyleGuide

2020-07-19 22:46 UTC, aroller commented on rostest/super_node_status.cpp
> +  while(ARMED_count && ros::ok())
Although I see the logic is correct, first glance is confusing `(while ARMED_count)` without a comparison leads me to not understand the goal of the test.

consider using one variable `armed_count` which starts at zero and increments.  A constant `target_count=3` and your while loop `while(armed_count <= target_count && ros::ok)` which gives me clear understanding of the goal

2020-07-19 22:48 UTC, aroller commented on rostest/super_node_status.cpp
> +  ASSERT_EQ(0, ARMED_count);
`0` in this context is a `magic variable`.  Using the `target_count` would provide words to the goal.  https://en.wikipedia.org/wiki/Magic_number_(programming)

2020-07-19 22:50 UTC, aroller commented on rostest/super_node_status.cpp
> +
Provide documentation so the reader can know what the test is doing without going through the code.  What's the goal, what does it prove, what does it mean if it fails.

2020-07-19 22:58 UTC, aroller commented on rostest/super_node_status.cpp
> +    loop_rate.sleep();
this seems fine to use the sleep, but what happens if we never receive a call?  Your test will never exit and hang the action?  So you should provide max attempts to ensure the maximum time allowed. This will require you to keep another count of attempts. You could also use time by keep tracking of the start time and have a max time allowed.  Either approach is simple and understandable and would achieve the goal of avoiding the infinite loop.   

The Assertion below would ensure the test goals are being met for any of the reasons we may have exited.

2020-07-19 22:59 UTC, aroller commented on rostest/super_node_status.cpp
> +void callback(const brain_box_msgs::VxState& msg)
its good practice to always provide documentation for your methods.

2020-07-19 23:04 UTC, aroller requested changes
Looks promising and fairly simple to add the rostests to ensure the nodes are working properly. Fix the items requested and/or ask questions as replies to the request.  

I'll help fix the makefile to pass the build and explain the problem when I figure it out.

2020-07-20 02:48 UTC, dillonroller commented on rostest/super_node_status.cpp
> +    loop_rate.sleep();
Just to make sure, this wouldn't handle the case of the `am_super` node not successfully launching, since we wouldn't be able to connect and read the state, so it would just hang. Currently it just checks that the state it receives is either `ARMED` or not, and ends after 10 attempts.

I was thinking maybe spawn a new thread and set a timer to `ros::shutdown()` after maybe 20 seconds of the Test() function starting, but it's probably not needed.

2020-07-20 03:19 UTC, aroller commented on rostest/super_node_status.cpp
> +    loop_rate.sleep();
It would seem there is a default time limit of 60 seconds.  See [answers](https://answers.ros.org/question/50865/change-timeout-of-rostest/?answer=54743#post-id-54743).   [ROS docs](http://wiki.ros.org/roslaunch/XML/test#Optional_attributes)
> time-limit="60.0" - Number of seconds before the test is considered a failure. Default is 60 seconds.

So you are actually covered even without your 10 attempt limit.  I guess we should remove the 10 limit to keep the complexity of the test to a minimum.  This test will likely be used as a reference to others.  Sorry I didn't think of this earlier.

2020-07-20 12:11 UTC, aroller commented on rostest/super_node_status.cpp
> +  attempt_count++;
@Dillon-Roller Just noticed you put the attempt count increment here...which makes sense why you didn't trust it. It was supposed to go in your while loop in your TEST method.

2020-07-20 15:14 UTC, aroller commented on rostest/super_node_status.cpp
> +    loop_rate.sleep();
I've updated this to rely on the default timeout.

2020-07-20 17:40 UTC, merged