test: added unit tests to validate string conversion
AutoModality/am_super pull request #42
Opened 2020-07-25 02:27 UTC by dillonroller

Currently failing the test. Going to find the bug

2020-07-25 03:38 UTC, aroller commented on include/super_lib/am_life_cycle.h
> +  static constexpr std::string_view STATE_SHUTTING_DOWN = "SHUTTING_DOWN";
Cool. Looks like your test already caught an unhandled case.

2020-07-25 03:40 UTC, aroller commented on include/super_lib/am_life_cycle.h
> +  static const std::vector<LifeCycleState> allLifeCycleStates();
document your methods here.  Don't use the existing lack of documentation as an excuse to not explain what the method does...even though it is simple...get into the habit of always providing good documentation.

2020-07-25 03:48 UTC, aroller commented on test/lifecycle_state_unit_tests.cpp
> +    ASSERT_EQ(allStates[i], state);
OK.  The method interface is confusing (not your fault)...the pass by reference thing, but your test does validate the conversation as expected.

2020-07-25 03:54 UTC, aroller requested changes
add the missing documentation and submit with "fix: handled string conversion for missing state" to ensure your fix is represented.  Normally just adding tests doesn't affect production, but since you found an error and fixed it...hence the fix prefix.

2020-07-25 15:20 UTC, aroller commented on test/lifecycle_state_unit_tests.cpp
> +TEST(LifeCycle, stateToString_BadStringReturnsFalse)
Notice my recommended naming style, not yet documented.  `methodName_DescriptionOfTest`

2020-07-25 15:24 UTC, aroller commented on test/lifecycle_state_unit_tests.cpp
> +  ASSERT_FALSE(bad_strings_should_return_false);
notice the verbose name tells a story.  As a developer, you are a story teller and the more you write your code to tell the story, the less you need to add comments.

2020-07-25 15:25 UTC, aroller commented on test/lifecycle_state_unit_tests.cpp
> +  ASSERT_EQ(state,default_state) << "State should be unchanged since the string is bad";
this is just a bonus, but worth identifying that the method should not be modifying the state when the string is bad.

2020-07-25 15:27 UTC, aroller commented on src/super_lib/am_life_cycle.cpp
> +  state = state_info.at(state_str);
Added a test demonstrating this logic breaks the interface's promise to return a false instead of throw an exception. You need to always be "defensive" in your programming looking to avoid exceptions, which are a pain in C++ .

2020-07-25 15:29 UTC, aroller commented on src/super_lib/am_life_cycle.cpp
> -    return false;
This is the _Ah ha!_ moment.  You removed logic and did not put it back.  When refactoring code you must stop and think about every change you make.  Most programmers get angry if you are changing their code to "improve it", but remove logic they handled correctly.  Of course I simply ask...where was the test to show me I broke it...which is why I added the missing test.

2020-07-25 18:45 UTC, dillonroller reviewed
Done

2020-07-25 18:56 UTC, dillonroller commented on test/lifecycle_state_unit_tests.cpp
> +  ASSERT_EQ(state,default_state) << "State should be unchanged since the string is bad";
Is this okay to do in general? Or should we break it up into multiple unit tests?

2020-07-25 20:57 UTC, aroller commented on src/super_lib/am_life_cycle.cpp
> +    state = state_info.at(state_str);
nitpick: it would make more sense to return true here than at the bottom given the new simpler method you've written.

2020-07-25 21:00 UTC, aroller commented on test/lifecycle_state_unit_tests.cpp
> +  ASSERT_EQ(state,default_state) << "State should be unchanged since the string is bad";
multiple tests make sense when the criteria is different.  You can and should provide multiple asserts when the same criteria is being applied, which it is in this case.

2020-07-25 21:07 UTC, aroller commented on src/super_lib/am_life_cycle.cpp
> +    case LifeCycleState::SHUTTING_DOWN:
Now consider this improvement. You've already defined the mappings of strings to states in your map, but here you leave the logic of mapping states to strings. Notice also here you reference a constant, but in your map you do not. You've now defined the values of the string in two different places.  

I suggest you consider a bimap that will allow you to have a map in both directions, since the strings are keys as are the enums.  

https://www.boost.org/doc/libs/1_66_0/libs/bimap/doc/html/index.html

2020-07-25 21:08 UTC, aroller commented on src/super_lib/am_life_cycle.cpp
> +  {"INVALID", LifeCycleState::INVALID},
These strings were already defined as constants. You must always define once and reference anywhere.  Defining the strings inline here is ok as long as it is the only place it would exist...which would be the case if you used a bimap. https://www.boost.org/doc/libs/1_66_0/libs/bimap/doc/html/index.html

2020-07-25 21:09 UTC, aroller requested changes
You must not declare the strings in two different places.  I suggest using the bimap to allow the bidrectional enum<-->string conversion. 

https://www.boost.org/doc/libs/1_66_0/libs/bimap/doc/html/index.html

2020-07-27 01:44 UTC, aroller approved these changes
clean, efficient, tested, documented...and found a missing string mapping.

2020-07-27 01:45 UTC, merged