remove static constant from super_node_mediator
AutoModality/am_super pull request #70
Opened 2020-09-25 01:59 UTC by dillonroller

2020-09-25 03:07 UTC, aroller commented on include/am_super/super_node_mediator.h
> +  static bool nodeNameIsSuper(std::string node_name, SuperNodeMediator& node_mediator);
I think this should be a member function. Only the check methods should remain static because of the way they are used.

2020-09-25 03:09 UTC, aroller commented on src/am_super/super_node_mediator.cpp
> +    pair<bool,map<string,string>> check_results = allManifestedNodesCheck(supervisor, node_mediator, transition.check);
You should just pass "this".  As a member function, you pass an reference to thy self.

2020-09-25 03:09 UTC, aroller commented on src/am_super/super_node_mediator.cpp
> +SuperNodeMediator::TransitionInstructions SuperNodeMediator::transitionReady(Supervisor supervisor, SuperNodeMediator& node_mediator)
this isn't needed.  It is a member function.

2020-09-25 03:11 UTC, aroller requested changes
Use this so you don't pass around of a reference of the mediator to itself. https://stackoverflow.com/questions/6905598/c-equivalent-to-java-this

2020-09-25 21:58 UTC, dillonroller commented on include/am_super/super_node_mediator.h
> +  static bool nodeNameIsSuper(std::string node_name, SuperNodeMediator& node_mediator);
If this methods becomes a member function, then all function that use this must be non-static, but checkReadyToArm is static

2020-09-25 22:29 UTC, dillonroller commented on include/am_super/super_node_mediator.h
> +  static bool nodeNameIsSuper(std::string node_name, SuperNodeMediator& node_mediator);
Resolved: made nodeNameIsSuper a member function that references SUPER_NODE_NAME const

2020-09-25 23:13 UTC, aroller commented on test/super_node_mediator_unit_tests.cpp
> +const string SUPER_NODE_NAME = "am_super";
consider using a different name than am_super for your  test for clarity and to validate `am_super` has no meaning.

2020-09-26 00:01 UTC, aroller approved these changes

2020-09-26 00:03 UTC, merged