feat: implemented multi-map
AutoModality/am_super pull request #77
Opened 2020-10-14 02:03 UTC by dillonroller

2020-10-14 19:20 UTC, aroller requested changes
Explain why the extra ready.

2020-10-14 19:20 UTC, aroller commented on src/am_super/super_node_mediator.cpp
> +    {SuperState::READY, {SuperState::READY, SuperNodeMediator::checkReadyToArm}}
Why Armed to Ready?

2020-10-14 19:20 UTC, aroller commented on src/am_super/super_node_mediator.cpp
> +SuperNodeMediator::StateTransition SuperNodeMediator::getStateTransition(const Supervisor &supervisor)
Am I missing the unit test?

2020-10-14 19:20 UTC, aroller commented on test/super_node_mediator_unit_tests.cpp
> +  expected_state = SuperState::AUTO;
Probably better as two separate tests with the name stating clearly the expected result

2020-10-14 19:27 UTC, dillonroller commented on src/am_super/super_node_mediator.cpp
> +    {SuperState::READY, {SuperState::READY, SuperNodeMediator::checkReadyToArm}}
This would eventually be a transition down the line, and we would insert the `OperatorCommand::Cancel` into the structure. I just needed another element in the child map to see if we can successfully complete the happy case with a non-one-to-one map, but it just hanged in `ARMED` never transitioning out of it. I tested the getStateTransition and it successfully returns the correct transition from `ARMED` to `AUTO` but for some reason we never actually transition. It seems the transitionReady unit tests are also passing so it's a bit strange.

2020-10-14 19:29 UTC, dillonroller commented on test/super_node_mediator_unit_tests.cpp
> +  expected_state = SuperState::AUTO;
Sounds good.

2020-10-14 20:20 UTC, aroller commented on test/super_node_mediator_unit_tests.cpp
> +
empty test

2020-10-14 20:21 UTC, aroller commented on test/super_node_mediator_unit_tests.cpp
> +void ASSERT_getStateTransition(const SuperState &current_state, const SuperState &expected_state, const OperatorCommand &operator_command = (OperatorCommand)-1)
thank you for abstracting and re-using.

2020-10-14 20:29 UTC, aroller commented on src/am_super/super_node_mediator.cpp
> +}
what happens if not found?

2020-10-16 20:58 UTC, aroller commented on src/am_super/super_node_mediator.cpp
> +  std::map<SuperState, StateTransition> transitions(state_transitions_.at(supervisor.system_state));
supervisor.transitions.at(supervisor.system_state)

2020-10-16 21:04 UTC, aroller commented on src/am_super/super_node_mediator.cpp
> +    {SuperState::READY, {SuperState::READY, SuperNodeMediator::checkReadyToArm}}
By putting the transitions into supervisor, that will give you the ability to create unit tests with state transitions test fixtures.  This will allow you to be confident your multimap works without adding state transitions that are not part of your task assignment.

2020-10-16 21:05 UTC, aroller commented on test/super_node_mediator_unit_tests.cpp
> +
since this is DISABLED, all good.

2020-10-19 23:38 UTC, aroller approved these changes

2020-10-19 23:39 UTC, merged